### PR TITLE
[GH-#173] fixed issue with getting /info not as node

### LINKED ISSUE #173: GET /info API function does not work

### PR DESCRIPTION
**Pull request by thepiwo**
closes #173

### CODE REVIEW

File: apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex [hunk 1]
```diff
@@ -26,16 +26,22 @@ defmodule Aehttpserver.Web.InfoController do
...
-
-    if(!(peer_nonce == own_nonce)) do
-      Peers.schedule_add_peer(peer, peer_nonce)
+    peer_port = Plug.Conn.get_req_header(conn, "peer_port")
+    peer_nonce = Plug.Conn.get_req_header(conn, "nonce")
+    if !Enum.empty?(peer_port) && !Enum.empty?(peer_nonce) do
+      peer_ip = conn.peer |> elem(0) |> Tuple.to_list |> Enum.join(".")
+      peer_port = peer_port   |> Enum.at(0) |> to_string()
+      peer_port = ":" <> peer_port
+      peer_nonce = peer_nonce |> Enum.at(0) |> String.to_integer()
```
Comment (untra) [inline apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex]: when `peer_port` was first declared, it was typed as a `[binary]`. see: https://hexdocs.pm/plug/Plug.Conn.html#get_req_header/2
When you reassign it here, it becomes an `integer`. This is how bugs get made unintentionally.

In general, we should try to avoid reassigning variables unless we have to, and even then they should only be reassigned if they are going to maintain the original datatype. Remember Elixir is dynamically typed, so any mistakes made like this will not be caught by the compiler. Theres no penalty for declaring a new local variable.

Comment (untra) [reply apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex]: same goes for `peer_port`, originally a `[binary]`, now a `string`.

Comment (thepiwo) [reply apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex]: yes, I knew about it and it was kind of unintentionally as the code was like this prior to me changing it, but I guess we should be more strict about this in general, thank you!
